// ============================================================================
// Dataset loader — data/species.json + rulesets.json are GENERATED by
// scripts/ingest.mjs from the paleo.gg scrape. data/plants.json is
// hand-curated (paleo.gg publishes no flora database).
// ============================================================================

import type { Species, Plant, Ruleset, DataManifest } from "./types";
import speciesJson from "@/data/species.json";
import plantsJson from "@/data/plants.json";
import rulesetsJson from "@/data/rulesets.json";
import periodsJson from "@/data/periods.json";
import manifestJson from "@/data/manifest.json";

export const SPECIES = speciesJson as unknown as Species[];
export const PLANTS = plantsJson as unknown as Plant[];
export const RULESETS = rulesetsJson as unknown as Ruleset[];
export const PERIODS = periodsJson as unknown as Record<string, [number, number]>;

export const MANIFEST: DataManifest = {
  asOf: manifestJson.asOf,
  source: manifestJson.provenance,
  speciesCount: SPECIES.length,
};

const speciesById = new Map(SPECIES.map((s) => [s.id, s]));
const rulesetById = new Map(RULESETS.map((r) => [r.id, r]));

export function getSpecies(id: string): Species | undefined {
  return speciesById.get(id);
}
export function getRuleset(id: string): Ruleset | undefined {
  return rulesetById.get(id);
}

/** [older, younger] mya bounds for a named geologic period, if known. */
export function periodRange(period: string): [number, number] | undefined {
  return PERIODS[period];
}

/** Midpoint age of a period, for "N my out of place" distances. */
export function periodMidpoint(period: string): number | undefined {
  const r = periodRange(period);
  return r ? (r[0] + r[1]) / 2 : undefined;
}

export function formatArea(m2: number): string {
  return `${Math.round(m2).toLocaleString()} m²`;
}
